# -*- coding: utf-8 -*-
"""Nthprimenum

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XPmp9K4PB4EAC9snDqFRp1E2fUK5x2nr
"""

import random

# -----------------------------------------------------------
# Small primes for quick filtering
# -----------------------------------------------------------
SMALL_PRIMES = [
    2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47,
    53, 59, 61, 67, 71, 73, 79, 83, 89, 97
]

# -----------------------------------------------------------
# Miller-Rabin Primality Test
# -----------------------------------------------------------
def miller_rabin(n, t=10):
    if n < 2:
        return False

    # Quick test for small primes
    for p in SMALL_PRIMES:
        if n == p:
            return True
        if n % p == 0:
            return n == p

    # Write n - 1 = 2^r * d
    d = n - 1
    r = 0
    while d % 2 == 0:
        r += 1
        d //= 2

    # Repeat t rounds
    for _ in range(t):
        a = random.randrange(2, n - 1)
        x = pow(a, d, n)
        if x == 1 or x == n - 1:
            continue

        for _ in range(r - 1):
            x = pow(x, 2, n)
            if x == n - 1:
                break
        else:
            return False

    return True

# -----------------------------------------------------------
# Prime detector D(k)
# -----------------------------------------------------------
def D(k, t=10):
    return 1 if miller_rabin(k, t) else 0

# -----------------------------------------------------------
# Formula: nth prime = min { k : sum(D(i)) = n }
# -----------------------------------------------------------
def nth_prime(n, t=10):
    count = 0
    k = 2

    while True:
        if k == 2 or k % 2 == 1:  # check only 2 and odd numbers
            if D(k, t) == 1:
                count += 1
                if count == n:
                    return k
        k += 1

# -----------------------------------------------------------
# User Input Section
# -----------------------------------------------------------
if __name__ == "__main__":
    n = int(input("Enter n to compute the nth prime: "))
    result = nth_prime(n)
    print(f"The {n}th prime number is: {result}")